# Generated by Django 5.0.2 on 2024-02-22 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0003_alter_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='code',
        ),
    ]
